filetype off
set smartcase
set hidden
syntax on
set hls
set is
set ic
set textwidth=79
set tabstop=4
set shiftwidth=4
set expandtab
set encoding=utf-8
set rtp+=/etc/vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'elzr/vim-json'
call vundle#end()
filetype plugin indent on
