set smartcase
set nocompatible
set bs=2
set hidden
syntax on
set hls
set is
set ic
set tabstop=4
set shiftwidth=4
set expandtab
set encoding=utf-8
nnoremap  <C-n> :next <cr>
nnoremap  <C-p> :prev <cr>
" === burasi calisilacak === "
"set rtp+=/etc/vim/bundle/Vundle.vim
"call vundle#begin()
"Plugin 'VundleVim/Vundle.vim'
"Plugin 'elzr/vim-json'
"call vundle#end()
"filetype off
"filetype plugin indent on

" == bunlar kullanisli durmuyor
"set autoindent
"set textwidth=79
